name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  quiz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install base
        run: yarn install --frozen-lockfile

      - name: Install quiz dependencies
        working-directory: ./quiz
        run: yarn install --frozen-lockfile

      - name: Install admin dependencies
        working-directory: ./admin
        run: yarn install --frozen-lockfile

      - name: Build Projects
        working-directory: ./quiz
        run: yarn build

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to server
        working-directory: ./quiz
        run: scp -P ${{ secrets.SSH_PORT}} -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.SSH_SERVER }}:${{ secrets.SSH_PATH }}

      - name: Install depenedencies
        working-directory: ./quiz/
        run: ssh -p ${{ secrets.SSH_PORT}} -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} "cd ${{ secrets.SSH_PATH }} && source ~/.nvm/nvm.sh && nvm use 16 && npm install -g yarn && yarn install --frozen-lockfile --production"
        
      - name: Database migration
        working-directory: ./quiz/
        run: ssh -p ${{ secrets.SSH_PORT}} -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} "cd ${{ secrets.SSH_PATH }} && source ~/.nvm/nvm.sh && nvm use 16 && yarn prisma:migration"

      - name: Restart App
        run: ssh -p ${{ secrets.SSH_PORT}} -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} "touch ${{ secrets.SSH_PATH }}/tmp/restart.txt"
